import asyncio
import json
import os
import urllib.request
from typing import AsyncGenerator, Dict, Any, Optional, List

from tools import file_tools
from agent.prompts import CLAW_NEXTJS_SYSTEM_PROMPT


def sanitize_css_content(css_text: str) -> str:
    """Fixes common CSS syntax typos and corruption generated by LLMs."""
    import re
    # 1. Fix RGBA typos
    def fix_rgba(match):
        parts = [p.strip() for p in match.group(1).split(',')]
        if len(parts) == 4:
            clean_parts = []
            for p in parts[:3]:
                nums = re.findall(r'\d+', p)
                clean_parts.append(nums[0] if nums else "255")
            clean_parts.append(parts[3])
            return f"rgba({', '.join(clean_parts)})"
        return match.group(0)

    css_text = re.sub(r'rgba\(([^)]+)\)', fix_rgba, css_text)

    # 2. Remove invalid CSS properties like background-end: or background-start:
    css_text = re.sub(r'background-(end|start|lag|arg)\s*:[^;]+;', '', css_text, flags=re.IGNORECASE)

    # 3. Clean syntax artifacts like << or >> or == inside @apply directives
    css_text = re.sub(r'<<|>>|==', '', css_text)

    return css_text



class ClawAgentEngine:
    """Claw Agent Engine specializing in Next.js & React Full-Stack Applications."""


    OLLAMA_BASE_URL = "http://localhost:11434"

    def __init__(self):
        self.agent_name = "claw"
        self.agent_role = "Next.js App Specialist"
        self.mascot_state = "claw"

    def is_ollama_running(self) -> bool:
        """Checks if Ollama service is accessible."""
        try:
            req = urllib.request.Request(f"{self.OLLAMA_BASE_URL}/api/version")
            with urllib.request.urlopen(req, timeout=2.0) as response:
                return response.status == 200
        except Exception:
            return False

    async def stream_nextjs_app_response(
        self,
        user_query: str,
        target_folder: str = ".",
        model_id: str = "gemma4:26b",
        indexer: Optional[Any] = None,
    ) -> AsyncGenerator[Dict[str, Any], None]:
        """Generates a complete, multi-file Next.js application based on the user prompt."""
        loop = asyncio.get_running_loop()

        yield {
            "type": "state",
            "mascot_state": "claw",
            "status": f"⚡ Claw Agent initializing Next.js architecture with model '{model_id}'...",
            "step": "plan"
        }
        await asyncio.sleep(0.05)

        # Notify Sub-Agent spawn for Claw Architecture Phase
        yield {
            "type": "sub_agent_spawn",
            "sub_agent": {
                "id": "claw-nextjs-architect",
                "name": "Claw Next.js Architect",
                "role": "Next.js & React Full-Stack Specialist",
                "description": f"Generating Next.js App Router files for: '{user_query}'",
                "target_file": "app/page.jsx",
                "dependencies": [],
                "status": "working",
                "progress": 25,
                "logs": ["⚡ Initializing Next.js 14 App Router layout & components structure..."],
                "generated_code": ""
            }
        }

        yield {
            "type": "token",
            "content": f"⚡ **Claw Agent (Next.js Architect)** is building your Next.js application in `{target_folder}`...\n\n"
        }

        if not self.is_ollama_running():
            yield {
                "type": "token",
                "content": "⚠️ **Ollama Offline Error**: Cannot reach local LLM server at http://localhost:11434. Please start Ollama to generate Next.js code.\n"
            }
            yield {"type": "state", "mascot_state": "idle", "status": "Ollama Offline", "step": "error"}
            return

        # Read existing codebase files in target folder for code fixing & modifications
        existing_snippets = []
        code_files = file_tools.get_folder_code_files(target_folder)
        EXCLUDE_PATHS = [".next", "node_modules", "dist", "build", "Next.js"]
        for cf in code_files:
            rel_p = cf["rel_path"].replace("\\", "/")
            if any(ex.lower() in rel_p.lower() for ex in EXCLUDE_PATHS):
                continue
            f_res = file_tools.read_file(cf["rel_path"], folder=target_folder)
            if f_res.get("status") == "success" and f_res.get("content"):
                existing_snippets.append(f"--- EXISTING SOURCE FILE: {rel_p} ---\n{f_res['content'][:4000]}\n")


        existing_context = ""
        if existing_snippets:
            existing_context = (
                "\n\n=== EXISTING WORKSPACE CODEBASE (CRITICAL PRESERVATION & FIX DIRECTIVE) ===\n"
                "The following files ALREADY exist in the target folder. Carefully inspect them to diagnose errors, fix bugs, or implement requested modifications. "
                "Retain existing working features, components, and CSS while applying requested fixes:\n"
                + "\n".join(existing_snippets)
            )

        is_fix_request = any(kw in user_query.lower() for kw in ["fix", "bug", "error", "change", "update", "add", "modify", "correct", "repair", "clean"])

        system_prompt = CLAW_NEXTJS_SYSTEM_PROMPT
        if is_fix_request and existing_snippets:
            user_prompt = (
                f"You are Claw Agent, the Next.js & React Full-Stack Expert. The user has reported an issue or requested a fix:\n\n"
                f"User Request / Issue Description: {user_query}\n\n"
                f"Target Directory: {target_folder}\n"
                f"{existing_context}\n\n"
                f"=== INSTRUCTIONS ===\n"
                f"1. Carefully analyze the existing workspace files above and the user's issue description.\n"
                f"2. Diagnose and fix any syntax errors, invalid CSS properties (e.g. background-end), broken React imports, or logic bugs.\n"
                f"3. Return the COMPLETE, fixed content for each file that needs updating using ### FILE: path/to/file format!\n"
                f"4. Do NOT wipe working code—preserve working features and layout while applying the fix."
            )
        else:
            user_prompt = (
                f"Build a complete, fully-functional, beautiful Next.js application for the following user request:\n\n"
                f"User Prompt: {user_query}\n\n"
                f"Target Working Directory: {target_folder}\n"
                f"{existing_context}\n\n"
                f"Make sure to output all necessary Next.js files (package.json, app/page.jsx, app/layout.jsx, app/globals.css, and any React components) using ### FILE: path/to/file format!"
            )

        req_payload = {
            "model": model_id,
            "messages": [
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": user_prompt}
            ],
            "options": {"temperature": 0.2, "num_ctx": 4096, "num_predict": 2048},
            "stream": True
        }



        req = urllib.request.Request(
            f"{self.OLLAMA_BASE_URL}/api/chat",
            data=json.dumps(req_payload).encode("utf-8"),
            headers={"Content-Type": "application/json"}
        )

        def make_stream_call():
            return urllib.request.urlopen(req, timeout=120.0)

        try:
            response = await loop.run_in_executor(None, make_stream_call)
        except Exception as e:
            yield {
                "type": "token",
                "content": f"❌ **LLM Connection Error**: {str(e)}\n"
            }
            yield {"type": "state", "mascot_state": "idle", "status": "Error", "step": "error"}
            return

        full_response_text = ""

        # Stream chunks from Ollama response
        def read_line(res):
            return res.readline()

        while True:
            line = await loop.run_in_executor(None, read_line, response)
            if not line:
                break
            try:
                chunk = json.loads(line.decode("utf-8"))
                token = chunk.get("message", {}).get("content", "")
                if token:
                    full_response_text += token
                    yield {"type": "token", "content": token}
            except Exception:
                continue

        # Extract multi-file blocks and save to disk
        from agent.core import extract_multi_file_blocks
        import re
        parsed_files = extract_multi_file_blocks(full_response_text)

        if not parsed_files:
            # Fallback code block extraction for Next.js files
            blocks = re.findall(r'```(jsx|json|css|javascript|js|html)?\n(.*?)```', full_response_text, re.DOTALL)
            parsed_files = {}
            for lang, code in blocks:
                code_clean = code.strip()
                if not code_clean:
                    continue
                if lang == "json" or '"dependencies"' in code_clean:
                    parsed_files["package.json"] = code_clean
                elif lang == "css" or "@import" in code_clean or "tailwindcss" in code_clean:
                    parsed_files["app/globals.css"] = code_clean
                elif "RootLayout" in code_clean or "export const metadata" in code_clean:
                    parsed_files["app/layout.jsx"] = code_clean
                elif "use client" in code_clean or "export default function" in code_clean:
                    if "app/page.jsx" not in parsed_files:
                        parsed_files["app/page.jsx"] = code_clean
                    else:
                        parsed_files["components/AppUI.jsx"] = code_clean

        # Filter out invalid filename matches like "Next.js"
        INVALID_FILENAMES = ["next.js", "react.js", "vue.js", "node.js"]
        # Guarantee Next.js App Router core files exist (app/page.jsx & app/layout.jsx) to prevent 404
        has_page = any(fn.replace("\\", "/") in ["app/page.jsx", "app/page.tsx", "app/page.js", "pages/index.jsx", "pages/index.js"] for fn in parsed_files.keys())
        has_layout = any(fn.replace("\\", "/") in ["app/layout.jsx", "app/layout.tsx", "app/layout.js"] for fn in parsed_files.keys())

        if not has_page:
            main_code = None
            for fn, code in parsed_files.items():
                if "export default" in code or "function" in code:
                    main_code = code
                    break
            if not main_code:
                main_code = (
                    '"use client";\n'
                    'import React, { useState } from "react";\n\n'
                    'export default function Home() {\n'
                    '  return (\n'
                    '    <main className="min-h-screen bg-slate-950 text-white p-8 flex flex-col items-center justify-center">\n'
                    '      <div className="glass-card p-8 rounded-2xl max-w-xl text-center shadow-2xl">\n'
                    '        <h1 className="text-4xl font-bold bg-gradient-to-r from-blue-400 to-indigo-400 bg-clip-text text-transparent mb-4">Next.js Application</h1>\n'
                    f'        <p className="text-slate-300 mb-6">{user_query}</p>\n'
                    '      </div>\n'
                    '    </main>\n'
                    '  );\n'
                    '}\n'
                )
            parsed_files["app/page.jsx"] = main_code

        if not has_layout:
            parsed_files["app/layout.jsx"] = (
                'import "./globals.css";\n\n'
                'export const metadata = {\n'
                '  title: "Next.js App powered by Claw Agent",\n'
                '  description: "Next.js Application created autonomously by Claw Agent",\n'
                '};\n\n'
                'export default function RootLayout({ children }) {\n'
                '  return (\n'
                '    <html lang="en">\n'
                '      <body className="bg-slate-950 text-slate-100 antialiased">{children}</body>\n'
                '    </html>\n'
                '  );\n'
                '}\n'
            )

        written_files = []


        for filename, content in parsed_files.items():
            res = file_tools.write_file(filename, content, folder=target_folder)
            if res.get("status") == "success":
                written_files.append(filename)
                yield {
                    "type": "execution_log",
                    "mascot_state": "executing",
                    "command": f"write_file('{filename}')",
                    "output": f"⚡ Claw Agent written file: {res.get('path')}"
                }

        if indexer:
            try:
                indexer.reindex()
            except Exception:
                pass

        # Complete sub-agent progress update
        yield {
            "type": "sub_agent_update",
            "sub_agent": {
                "id": "claw-nextjs-architect",
                "name": "Claw Next.js Architect",
                "role": "Next.js & React Full-Stack Specialist",
                "description": f"Generated {len(written_files)} Next.js project files",
                "target_file": written_files[0] if written_files else "app/page.jsx",
                "dependencies": [],
                "status": "completed",
                "progress": 100,
                "logs": [f"✅ Successfully wrote {len(written_files)} files: {', '.join(written_files)}"],
                "generated_code": full_response_text[:300] + "..."
            }
        }

        yield {
            "type": "token",
            "content": (
                f"\n\n🚀 **Next.js App Generated by Claw Agent!**\n"
                f"📁 **Location**: `{target_folder}`\n"
                f"📦 **Files Created**: `{', '.join(written_files)}`\n\n"
                f"### ⚙️ How to Run Your Next.js App:\n"
                f"```bash\n"
                f"cd {target_folder}\n"
                f"npm install\n"
                f"npm run dev\n"
                f"```\n"
                f"Open `http://localhost:3000` in your browser to view your Next.js application!\n"
            )
        }

        yield {"type": "state", "mascot_state": "idle", "status": "Next.js App Built by Claw Agent", "step": "idle"}
